[[mounts]]
  source = "node_modules/@thulite/tailwindcss/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@thulite/tailwindcss/layouts"
  target = "layouts"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "hugo_stats.json"
  target = "assets/watching/hugo_stats.json"
